import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ThemeRegistry from './ThemeRegistry/ThemeRegistry'
import Navbar from './Components/Navbar/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Interamerica Capital',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"> 
      <body className={inter.className}>
       <Navbar variant="b2blight" />
        <ThemeRegistry>
           
            {children}
            
        </ThemeRegistry>
      </body>
    </html>
  )
}
